spring.application.name=AccountTrade

server.port=8081
logging.level.root=info
spring.main.banner-mode=off

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/account_trading_system
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quangkhoa5112@gmail.com
spring.mail.password=iveu hqeg hjqa ldfj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# iveu hqeg hjqa ldfj

# Cloudinary Configuration for image upload
cloudinary.cloud-name=dj5wpyfvh
cloudinary.api-key=961397322237811
cloudinary.api-secret=ABahQ3j9UOU245iSBmlAwqCCN0Q

# File upload configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-part-count=50
server.tomcat.max-http-form-post-size=25MB
server.tomcat.max-swallow-size=25MB
