#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Mar 26 21:34:47 ICT 2026
maven-metadata-spring-snapshots.xml/@default-spring-snapshots-https\://repo.spring.io/snapshot/.lastUpdated=1774535687376
maven-metadata-spring-snapshots.xml.error=Could not transfer metadata org.springframework.boot\:spring-boot-starter-parent\:4.0.3-SNAPSHOT/maven-metadata.xml from/to spring-snapshots (https\://repo.spring.io/snapshot)\: Permission denied\: no further information
